### ISSUE TITLE
Key Fingerprint Needs to be in MD5 Format

### ISSUE THREAD

**Issue by qdzlug** [ContainerSolutions/dcos-in-triton#1]
Hi,

If you use a SHA256 format, the `terraform apply` fails with:

```
caused by: request "https://api.joyentcloud.com/jay.schmidt/machines" returned unexpected status 401 with body "{\"code\":\"InvalidCredentials\",\"message\":\"Invalid KeyId /jay.schmidt/keys/SHA256:8lJK3XwkvadReLNMj5WY0xFkiDl/Q5UGcuKBtpa7oO4 in authorization header\"}"
```

The SHA256 is acceptable to the node-triton tools, so users may have these style in their TRITON_KEY_ID / SDC_KEY_ID variable.

Fix is to generate the MD5 version of the hash:

```
$ ssh-keygen -l -E md5 -f  ~/.ssh/id_rsa.pub
2048 MD5:db:95:dd:3d:dd:6e:52:69:21:96:2a:46:4a:8d:21:7e example@example.local (RSA)
```

And use that hash as your fingerprint.

Jay

**Comment by mongrelion** [comment]
Hi, @qdzlug.

Would you be so kind to open a pull request to update the README file with a special note about this?

**Comment by mongrelion** [comment]
Issue address on PR #2
